[package]
name = "esse-app"
version.workspace = true
edition.workspace = true
publish.workspace = true

[[bin]]
name = "esse"
path = "src/main.rs"

[dependencies]
esse-core.workspace = true
markdown-lite.workspace = true
gpui.workspace = true
gpui_platform.workspace = true
chrono.workspace = true
dirs.workspace = true
env_logger.workspace = true
log.workspace = true
